all:
  vars:
    ansible_connection: ssh
    ansible_ssh_user: ec2-user
    ansible_become: true
    ansible_ssh_private_key_file: /home/ec2-user/Confluent.pem
    security_mode: plaintext
preflight:
  hosts:
    172.31.84.43:
    172.31.85.240:
    172.31.85.96:
    172.31.90.255:
zookeeper:
  hosts:
    172.31.84.43:
    172.31.85.240:
    172.31.85.96:
broker:
  hosts:
    172.31.84.43:
      kafka:
        broker:
          id: 1
    172.31.85.240:
      kafka:
        broker:
          id: 2
    172.31.85.96:
      kafka:
        broker:
          id: 3
schema-registry:
  hosts:
    172.31.90.255:
control-center:
  hosts:
    172.31.90.255:
      confluent:
        control:
          center:
            config:
              confluent.controlcenter.connect.cluster: 172.31.90.255:8083
connect-distributed:
  hosts:
    172.31.90.255:
kafka-rest:
  hosts:
    172.31.90.255:
ksql:
  hosts:
    172.31.90.255:
tools:
  hosts:
    172.31.84.43:
